### ISSUE TITLE
Inkdrop `PATH` variable?

### ISSUE THREAD

**Issue by gpmcadam** [jmerle/inkdrop-graphviz#2]
The docs say that `dot` should be included in the `PATH` variable, and in my shell, `dot` is indeed available as a command.

How does Inkdrop get its `PATH` environment variable set, and where can I add another path to this?

Thanks!

**Comment by jmerle** [comment]
That's weird. inkdrop-graphviz uses [execa](https://github.com/sindresorhus/execa), which in turn loads the environment from Node.js' [`process.env`](https://nodejs.org/docs/latest-v12.x/api/process.html#process_process_env). I have no idea what goes wrong in your case as it should "just work".

How did you install `dot` and configure it on your PATH? I'm just guessing here, but did you perhaps append its path to your `PATH` in your personal .bashrc or .zshrc file (assuming you're using Linux or macOS)?

**Comment by gpmcadam** [comment]
I'm using macOS and I've installed `dot` via Brew.

```
$ which dot
/usr/local/bin/dot
```

In Inkdrop, if I open the dev tools, and evaluate `process.ENV.path`, I get:

```
$ process.env.PATH
"/usr/bin:/bin:/usr/sbin:/sbin"
```

**Comment by jmerle** [comment]
Hmm, so your `process.env.PATH` inside Inkdrop is different from your `PATH` in a terminal. This seems to have occurred with Atom too some years ago: https://github.com/electron/electron/issues/550. Is `process.env.PATH` correct if you run the Inkdrop binary from a terminal (make sure to close a possibly running Inkdrop first)?

**Comment by gpmcadam** [comment]
If I run `open /Applications/Inkdrop.app` then the output is as it should be, including all of my shell `PATH` variables.

**Comment by jmerle** [comment]
Considering this is an issue with the way Inkdrop is launched and not with the plugin itself, there is very little I can do outside of "hacky" workarounds. I don't use macOS myself, but I would advise you to start from the terminal and/or find a way to run a shell script from a dock launcher ([seems to be doable with Automator](https://support.apple.com/guide/automator/use-a-shell-script-action-in-a-workflow-autbbd4cc11c/mac)).
