### ISSUE TITLE
bug: diagram not exported in PDF

### ISSUE THREAD

**Issue by gpmcadam** [jmerle/inkdrop-graphviz#3]
When creating a document with a graphviz in and exporting as PDF, the diagram is not included as part of the PDF

**Comment by jmerle** [comment]
Unfortunately this can't be fixed because the diagrams are created asynchronously, and asynchronously loaded resources [cannot be printed or exported](https://forum.inkdrop.app/t/embed-github-gists/1698/7?u=jmerle).
